### ISSUE TITLE
Komolyan még mindig ilyenekkel foglalkozol?

### ISSUE THREAD

**Issue by ddave5** [rkeeves/selenide-dirty-tricks#1]
Azt hittem, hogy eleget szenvedtél nálunk! Inkább valamikor írj egy e-mailt és beszéljünk, úgyis lesz egy-két jó sztorim!
Félegyházi Dávid

**Comment by rkeeves** [comment]
1. [Yes.](https://youtu.be/kjPSJHSsDmU?t=592)

2. Search for a mail containing the string 'Tenet' in your whole mailbox, spam included.
